# Generated by Django 4.1 on 2024-01-30 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('taste_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('appearance_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('used_miso', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedMisoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.items')),
            ],
        ),
        migrations.CreateModel(
            name='UsedMisoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('taste_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('appearance_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.items')),
            ],
        ),
    ]
