# Generated by Django 4.1 on 2024-01-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_items_id_alter_usedmisodetail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='appearance_rating',
        ),
        migrations.RemoveField(
            model_name='items',
            name='taste_rating',
        ),
        migrations.RemoveField(
            model_name='items',
            name='thoughts',
        ),
    ]
