# Generated by Django 4.1 on 2024-01-31 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usedmisodetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmisodetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
