# Generated by Django 4.1 on 2024-02-16 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usedmisodetail_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='商品名')),
                ('image', models.ImageField(upload_to='item_images/', verbose_name='画像')),
                ('used_miso', models.BooleanField(default=False, verbose_name='使った味噌')),
                ('thoughts', models.TextField(blank=True, null=True)),
                ('taste_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('appearance_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usedmisodetail',
            name='item',
        ),
        migrations.RemoveField(
            model_name='usedmisodetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usedmisolist',
            name='item',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='UsedMisoDetail',
        ),
        migrations.DeleteModel(
            name='UsedMisoList',
        ),
    ]
